layout_spectrum: 0.9081632
color:
  saturation: 1
  brandStrength: 0.9399266
  lightness: 0.4634801
  rhythmicContrast: 0.6879699
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.7867884
name: GooglyMoogly
